---
# Use a very basic window manager and login manager
# idesk is needed for doing a desktop icon
- name: install xorg and window managers
  ansible.builtin.apt:
    name:
    - xserver-xorg-core
    - xserver-xorg-input-libinput
    - xserver-xorg-input-mouse
    - xserver-xorg-input-evdev
    - openbox
    - slim
    - idesk
    - fbpanel
    state: present
    cache_valid_time: 3600

- name: install extra fonts
  ansible.builtin.apt:
    name:
    - fonts-arphic-ukai
    - fonts-arphic-uming
    - fonts-ipafont-gothic
    - fonts-ipafont-mincho
    - fonts-unfonts-core
    state: present
    cache_valid_time: 3600

# We want to auto login to openbox
- name: set autologin for slim
  ansible.builtin.lineinfile:
    dest: /etc/slim.conf
    regexp: "^auto_login "
    insertafter: "^#auto_login "
    line: "auto_login yes"
- name: set default username for slim
  ansible.builtin.lineinfile:
    dest: /etc/slim.conf
    regexp: "^default_user "
    insertafter: "^#default_user "
    line: "default_user {{ ansible_user }}"
- name: remove xsession directory from slim
  ansible.builtin.lineinfile:
    dest: /etc/slim.conf
    regexp: "^sessiondir "
    line: "#sessiondir "
    backrefs: yes

# Copy over a basic menu which just lets staff reboot the machine
- name: copy openbox menu config
  ansible.builtin.copy:
    src: openbox/menu.xml
    dest: /etc/xdg/openbox/menu.xml

# Copy over a stripped down version of openbox keyboard/mouse config
# Disables multiple desktops and their shortcuts
- name: copy openbox mapping config
  ansible.builtin.copy:
    src: openbox/rc.xml
    dest: /etc/xdg/openbox/rc.xml

# Set openbox to disable screen blanking and launch chrome on boot
- name: copy openbox autostart
  ansible.builtin.template:
    src: autostart.sh.j2
    dest: /etc/xdg/openbox/autostart

# Basic idesk config. Sets it so single click launches Chrome
- name: copy idesk config
  ansible.builtin.copy:
    src: desktop/dot.ideskrc
    dest: /home/{{ catalog_station_default_user }}/.ideskrc
    owner: "{{ catalog_station_default_user }}"
    group: "{{ catalog_station_default_user }}"

# Create .idesktop directory for next icon command
- name: Create .idesktop directory
  ansible.builtin.file:
    path: /home/{{ catalog_station_default_user }}/.idesktop/
    state: directory
    owner: "{{ catalog_station_default_user }}"
    group: "{{ catalog_station_default_user }}"

- name: Create fbpanel config directory
  ansible.builtin.file:
    path: /home/{{ catalog_station_default_user }}/.config/fbpanel
    state: directory
    owner: "{{ catalog_station_default_user }}"
    group: "{{ catalog_station_default_user }}"

- name: Copy fbpanel config
  ansible.builtin.copy:
    src: desktop/fbpanel.default
    dest: /home/{{ catalog_station_default_user }}/.config/fbpanel/default
    owner: "{{ catalog_station_default_user }}"
    group: "{{ catalog_station_default_user }}"

- name: allow user to killall for reset
  ansible.builtin.template:
    src: killall.sudo.j2
    dest: /etc/sudoers.d/killall
    validate: 'visudo -cf %s'

- name: Calibrate ELO Display
  ansible.builtin.copy:
    src: calibrate-display.sh
    dest: /usr/bin/calibrate-display
    mode: 'a+x'
  when: catalog_station_elo_monitor
