---
# Use a very basic window manager and login manager
# idesk is needed for doing a desktop icon
- name: install xorg and window managers
  apt: name={{item}} state=installed
  with_items:
    - xorg
    - openbox
    - slim
    - idesk
    - fbpanel

# Base ubuntu does some languages ok but not things like chinese simplified, korean, etc.
- name: install east asian fonts
  apt: name={{item}} state=installed
  with_items:
    - fonts-arphic-ukai 
    - fonts-arphic-uming 
    - fonts-ipafont-gothic 
    - fonts-ipafont-mincho 
    - fonts-unfonts-core

# We want to auto login to openbox
- name: set autologin for slim
  lineinfile: dest=/etc/slim.conf regexp="^auto_login " insertafter="^#auto_login " line="auto_login yes"
- name: set default username for slim
  lineinfile: dest=/etc/slim.conf regexp="^default_user " insertafter="^#default_user " line="default_user {{catalog_station_default_user}}"
- name: remove xsession directory from slim
  lineinfile: dest=/etc/slim.conf regexp="^sessiondir " line="#sessiondir " backrefs=yes

# Right now we use Google as our go-to browser.
# Install from official sources
- name: add google repository key
  apt_key: 
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub 
    state: present
- name: add google chrome repository
  apt_repository: 
    repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main' 
    state: present
    filename: 'google-chrome'
- name: install google chrome stable
  apt: 
    name: google-chrome-stable 
    state: latest

# Copy over a basic menu which just lets staff reboot the machine
- name: copy openbox menu config
  copy: src=desktop/menu.xml dest=/etc/xdg/openbox/menu.xml

# Copy over a stripped down version of openbox keyboard/mouse config
# Disables multiple desktops and their shortcuts
- name: copy openbox mapping config
  copy: src=desktop/rc.xml dest=/etc/xdg/openbox/rc.xml

# Basic idesk config. Sets it so single click launches Chrome
- name: copy idesk config
  copy: src=desktop/dot.ideskrc dest=/home/{{catalog_station_default_user}}/.ideskrc

# Create .idesktop directory for next icon command
- file: path=/home/{{catalog_station_default_user}}/.idesktop/ state=directory

# Copy script to launch chrome with needed arguments
- name: chrome launcher for DRY reuse
  copy: src=desktop/launch-chrome.sh dest=/usr/bin/launch-chrome mode=a+x

# Create icon / shortcut for Chrome to be launched
- name: copy chrome icon
  copy: src=desktop/chrome.png dest=/home/{{catalog_station_default_user}}/.idesktop/chrome.png
- name: copy chrome shortcut
  copy: src=desktop/chrome.lnk dest=/home/{{catalog_station_default_user}}/.idesktop/chrome.lnk

# Set openbox to disable screen blanking and launch chrome on boot
- name: copy openbox autostart
  copy: src=desktop/autostart.sh dest=/etc/xdg/openbox/autostart

# Copy script to fix mouse orientation
- name: install calibration script
  copy: src=calibrate-display.sh dest=/usr/bin/calibrate-display mode=a+x
# Create policies directory and set up our chrome policies
- file: path=/etc/opt/chrome/policies state=directory
- name: copy chrome policy
  copy: src=chrome-policies/managed dest=/etc/opt/chrome/policies/
- template: src=homepage.json.j2 dest=/etc/opt/chrome/policies/managed/homepage.json

# Cron to launch chrome if it is dead
- name: copy check chrome script
  copy: src=check-chrome.sh dest=/usr/bin/check-chrome mode=a+x
- name: cron to relaunch chrome if not open
  cron: name="check chrome" minute="*" job="/usr/bin/check-chrome > /dev/null 2>&1 &"
  become: false

# Install xprintidle for idle reset script
- name: install xprintidle
  apt: name=xprintidle state=installed

# Install sudoers file for killall command
- name: allow catalog user to killall for reset
  copy: src=killall.sudo dest=/etc/sudoers.d/killall validate='visudo -cf %s'

# Setup FBPanel
- name: copy fbpanel config
  file: path=/home/{{catalog_station_default_user}}/.config/fbpanel state=directory
- copy: src=desktop/fbpanel.default dest=/home/{{catalog_station_default_user}}/.config/fbpanel/default

# Make time be local. TODO: make this a variable
- name: fix timezone to Eastern.
  command: echo "America/Detroit" > /etc/timezone
- file: path=/etc/localtime src=/usr/share/zoneinfo/America/Detroit state=link force=true

# Install CUPs and disable some of the automatic browsing. Slows down shutdowns.
# - name: install CUPs
#   apt: name=cups state=installed
# - name: disable avahi-daemon
#   command: systemctl disable avahi-daemon
# - name: disable cups-browsed
#   command: systemctl disable cups-browsed

# Install CUPS Printer for West. Need to make this a var/template
# - name: copy lexmark driver deb
#   copy: src=lexmark-ppd.deb dest=/tmp/lexmark-ppd.deb
# - name: install lexmark drivers
#   command: dpkg -i /tmp/lexmark-ppd.deb
# - command: service cups stop
# - name: copy printer config
#   copy: src=printers.conf dest=/etc/cups/printers.conf
# - name: copy global ppd files for queues
#   command: cp /usr/local/lexmark/ppd/lexmark-PPD-Files-LMAEG/GlobalPPD_1.4/Lexmark_XM1100_Series.ppd /etc/cups/ppd/west-public-1.ppd
# - command: cp /usr/local/lexmark/ppd/lexmark-PPD-Files-LMAEG/GlobalPPD_1.4/Lexmark_XM1100_Series.ppd /etc/cups/ppd/west-public-2.ppd
# - command: service cups start

# Time Sync
# - name: install ntpdate
#   apt: name=ntpdate state=installed
# - name: set up ntpdate cron
#   cron: name="sync time" hour="12" job="/usr/sbin/ntpdate {{catalog_station_ntp_server}} > /dev/null 2>&1 &"


